# Autres activités

## Activités de prestation de service et d'expertise

## Responsabilité, fonctions et réseaux au service de l'établissement (y compris à l'international)

-   *Mars 2019 - ...* Membre de la commission de titularisation;
-   *Mars 2021 - ...* Membre de la commission des salles informatiques;

## Participation à des jurys (membre ou rapporteur) internes et externes

-   *Juin 2023* Membre interne pour un jury de recrutement de Maître(sse) de conférences en statistiques au sein du département MMIP d'Agroparistech;

## Responsabilités et fonctions externes à l'établissement

-   *2019 -...* Coanimation du groupe de recherche francilien *All about that Bayes* de la statistique bayésienne (principaux membres: Sorbonne Université, Paris Sciences et Lettres);
-   *2022 -...* Coanimation du groupe de recherche *Monte Plateau* regroupant des chercheurs du plateau de Saclay autour des méthodes de Monte Carlo.

## Rayonnement national et international

### Présentations en conférences et ateliers de recherche

2
-   *Juin 2019* Journées de la statistique française (Nancy);
-   *Mars 2022* Statistiques au sommet de Rochebrune (Megève);

### Présentations en séminaire de recherche

-   *Mai 2020* Séminaire de statistiques d'Agroparistech (Paris);\$
-   *Juin 2021* Séminaire de statistiques de l'IMAG (Montpellier);
-   *Octobre 2021* Séminaire d'ECOFOG (Kourou);
-   *Septembre 2022* Séminaire d'hommage à Eric Parent (Paris);
-   *Janvier 2023* Séminaire de l'IRMAR (Rennes);
-   *Février 2023* Séminaire du laboratoire Raphaël Salem (Rouen);
-   *Mars 2023* Séminaire du LMBA (Vannes);

## Appartenance à des commissions et des groupes de travail institutionnels

-   Membre de la société française de statistique (SFDS);
-   Membre fondateur du bureau du groupe "Statistique bayésienne" de la SFDS;
