# Annexe A {.unnumbered}

Tous les chiffres sont présentés ici depuis Septembre 2019;

- Heures enseignement en formation initiale: 192h /an
- Heures enseignement en formation continue: 0h
- Nombre et type de responsabilités: 5
    - 2 responsabilités de cursus stats en socle commun de domaine;
    - 1 responsabilité d'une UC de dominante Biotech (3A)
    - 2 responsabilités d'une UC de Master
- Nombre moyen d'étudiants encadrés: 1
- Nombre de mission d'enseignement hors établissement: 2 (42 heures sur 3 ans);
- Nombre de publications d'enseignement: 0
- Nombre et % d'encadrements (sur 3 ans):
    - Thèse université: 1 (33%);
    - Master 2: 1 (100%);
    - Licence, Master 1: 2 (100%);
- Nombre de publications internationales à comité de lecture: 5
    - 3 en 1er ou 2e auteur;
    - 2 en autres places;
    - +1 chapitre de livre;
- Nombre de coommunications: en conférences: 2
- Nombre et type de jury: 1 jury de recrutement (à venir en Mai 2023);
- Nombre de commissions et groupes de travail: 2
