# Présentation du candidat

## État civil

- Pierre GLOAGUEN, né le 18 Septembre 1987 à Vannes (56);
- Maître de conférences du ministère de de l'enseignement supérieur agricole ( depuis Septembre 2018;
- Échelon 5;
- Section CNECA n°3;
- Etablissement: Agroparistech;
- Adresse: 22 place de l'Agronomie, 91400, Palaiseau;
- Courriel: pierre.gloaguen@agroparistech.fr;
- Téléphone: 01 89 10 09 49;


## Cursus professionnel, fonctions exercées, mobilité

- *09/2018- ...*: Maître de conférences en Statistiques à Agroparistech;
- *06/2017 - 08/2018*:  Post Doctorat à l'Université Bretagne Sud. 
- *03/2016 - 03/2017*: Post Doctorat à l'Institut National de la Recherche Agronomique (INRA), AgroParisTech. 
- *11/2012 - 11/2015*: Thèse à l'Institut Français de Recherche pour l'Exploitation de la Mer (IFREMER),  Nantes.  **Modélisation mécaniste et stochastique des trajectoires pour l'halieutique.**

## Diplômes et formations complémentaires

### Diplômes {-}

- **Doctorat** obtenu en Décembre 2015, décerné par l'Agrocampus-Ouest, spécialité Écologie. Thèse encadrée par Stéphanie Mahévas, Etienne Rivot et Marie-Pierre Etienne.
Jury de thèse  composé de
    - *Rapporteurs*: Olivier Gimenez (Directeur de Recherche au Centre d'\'Ecologie Fonctionnelle et Évolutive);
et  Adeline Leclercq Samson (Professeure en Statistiques à l'Université Grenoble Alpes);
    - *Examinateurs*: Didier Gascuel (Professeur Agrocampus-Ouest),  Juan Manuel Morales (Enseignant chercheur , Universidad Nacional del Comahue) et Samuel Soubeyrand (Directeur de Recherche INRAe);
- **Master** en Mathématiques, Statistiques et applications, obtenu en Juin 2012, décerné par l'Université Montpellier II (en partenariat avec SupAgro Montpellier);
- **Licence** en Mathématiques, Statistiques et applications, obtenu en Juin 2008, décerné par l'Université Rennes I;